### ISSUE TITLE
Upgrade to L4T 28.3.0

### ISSUE THREAD

**Issue by sjdrc** [balena-os/balena-jetson-skx2#166]
Hi, while waiting for #125, we have switched our base to L4T R28.3.0. This is largely the same as 28.2.1, but contains some essential fixes (includes fixing a memory leak in tegra mmapi).

We probably won't want to switch to 32.x now for a while now that we have a new stable base. Would it be possible to upgrade the version of L4T you use to 28.3.0?

**Comment by floion** [comment]
@sjdrc for what device type?

**Comment by sjdrc** [comment]
@floion Jetson TX2

**Comment by acostach** [comment]
@sjdrc I see that meta-tegra only has a branch with support for 28.3.0, not 28.3.1.. Does this include the fixes you need?

Also, are these fixes included in the libraries side or in the kernel? 

Because if they are included in the userspace then you should be able to bring in only the BSP archive for 28.3.1 and unpack it in the app image. If that's the case I believe it should be compatible with the 28.2 kernel in the hostOS.

**Comment by sjdrc** [comment]
@acostach 28.3.0 does include the fix that we need. It's in the kernel:
https://developer.nvidia.com/embedded/dlc/l4t-release-notes-28-3 (section 2.1.3).

**Comment by acostach** [comment]
All good then @sjdrc , we'll have a look at switching it to thud 28.3.

**Comment by acostach** [comment]
BalenaOS v2.45.0+rev1 using 4.4.159-**l4t-r28.3**+gd6a4a9d Kernel is now available in production. Yocto layers are now based on thud branches.
